[package]
name = "youtube_summarizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2.5", features = ["json"] }